"""initial schema

Revision ID: d7d9c7c6cf60
Revises:
Create Date: 2026-08-19 07:06:23.532376

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d7d9c7c6cf60"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # PG enums first: autogenerate emits them inline per column, which double-creates
    # any type used by more than one table (docs/SCHEMA.md).
    sa.Enum("PHC", "CHC", "DISTRICT", "REGIONAL", "MEDICAL_COLLEGE", name="hospital_level").create(
        op.get_bind()
    )
    sa.Enum("PRESENCE_CHANGE", "MANUAL", "PERIODIC", name="plan_trigger").create(op.get_bind())
    sa.Enum("GENERAL", "ICU", "HDU", "MATERNITY", "ISOLATION", name="bed_kind").create(
        op.get_bind()
    )
    sa.Enum("FREE", "OCCUPIED", "RESERVED", "CLEANING", "OOO", name="bed_state").create(
        op.get_bind()
    )
    sa.Enum(
        "A_POS", "A_NEG", "B_POS", "B_NEG", "AB_POS", "AB_NEG", "O_POS", "O_NEG", name="blood_group"
    ).create(op.get_bind())
    sa.Enum("WHOLE", "PRBC", "FFP", "PLATELET", name="blood_component").create(op.get_bind())
    sa.Enum("ERAKTKOSH", "SYNTHETIC", name="blood_source").create(op.get_bind())
    sa.Enum("ADMIN", "DOCTOR", "STAFF", "PATIENT", name="user_role").create(op.get_bind())
    sa.Enum("OPEN", "ROUTED", "CLOSED", name="emergency_status").create(op.get_bind())
    sa.Enum("HMIS", "SYNTHETIC", name="footfall_source").create(op.get_bind())
    sa.Enum("HI", "EN", name="language").create(op.get_bind())
    sa.Enum("OPD", "WARD", "OT", "GATE", "LOBBY", name="zone_kind").create(op.get_bind())
    sa.Enum(
        "PRESENT_IN_DEPT",
        "PRESENT_ELSEWHERE",
        "ON_ROUNDS",
        "IN_SURGERY",
        "ON_LEAVE",
        "OFF_SHIFT",
        "UNKNOWN",
        name="presence_state",
    ).create(op.get_bind())
    sa.Enum("BLE", "RFID", "FACE", "WIFI", "ROSTER", "MANUAL", name="signal_source").create(
        op.get_bind()
    )
    sa.Enum("OPD", "WARD", "SURGERY", "ON_CALL", "LEAVE", name="shift_kind").create(op.get_bind())
    sa.Enum("OPEN", "FULL", "BLOCKED", name="slot_status").create(op.get_bind())
    sa.Enum("PWA", "WHATSAPP", "SMS", "IVR", "VOICE", "KIOSK", "STAFF", name="channel").create(
        op.get_bind()
    )
    sa.Enum("EMERGENCY", "REFERRED", "PRIORITY", "GENERAL", name="priority_class").create(
        op.get_bind()
    )
    sa.Enum(
        "BOOKED",
        "CHECKED_IN",
        "IN_CONSULT",
        "COMPLETED",
        "NO_SHOW",
        "CANCELLED",
        "RESCHEDULED",
        name="appointment_status",
    ).create(op.get_bind())
    sa.Enum("ROUTINE", "URGENT", "EMERGENCY", name="referral_urgency").create(op.get_bind())
    sa.Enum(
        "REQUESTED",
        "RESERVED",
        "CONFIRMED",
        "ARRIVED",
        "EXPIRED",
        "CANCELLED",
        name="referral_status",
    ).create(op.get_bind())
    sa.Enum("QUEUED", "SENT", "DELIVERED", "FAILED", name="notification_status").create(
        op.get_bind()
    )
    sa.Enum("WAITING", "CALLED", "SERVING", "DONE", "SKIPPED", name="queue_state").create(
        op.get_bind()
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hospitals",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("district", sa.String(length=100), nullable=False),
        sa.Column("lat", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("lng", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column(
            "level",
            postgresql.ENUM(
                "PHC",
                "CHC",
                "DISTRICT",
                "REGIONAL",
                "MEDICAL_COLLEGE",
                name="hospital_level",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("contact", sa.String(length=100), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "plan_runs",
        sa.Column(
            "trigger",
            postgresql.ENUM(
                "PRESENCE_CHANGE", "MANUAL", "PERIODIC", name="plan_trigger", create_type=False
            ),
            nullable=False,
        ),
        sa.Column("scope", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("solver_status", sa.String(length=32), nullable=False),
        sa.Column("objective", sa.Numeric(precision=14, scale=3), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("moved_count", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "beds",
        sa.Column("hospital_id", sa.UUID(), nullable=False),
        sa.Column("ward", sa.String(length=80), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column(
            "kind",
            postgresql.ENUM(
                "GENERAL",
                "ICU",
                "HDU",
                "MATERNITY",
                "ISOLATION",
                name="bed_kind",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "state",
            postgresql.ENUM(
                "FREE",
                "OCCUPIED",
                "RESERVED",
                "CLEANING",
                "OOO",
                name="bed_state",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["hospital_id"], ["hospitals.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("hospital_id", "code"),
    )
    op.create_table(
        "blood_stock",
        sa.Column("hospital_id", sa.UUID(), nullable=False),
        sa.Column(
            "group",
            postgresql.ENUM(
                "A_POS",
                "A_NEG",
                "B_POS",
                "B_NEG",
                "AB_POS",
                "AB_NEG",
                "O_POS",
                "O_NEG",
                name="blood_group",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "component",
            postgresql.ENUM(
                "WHOLE", "PRBC", "FFP", "PLATELET", name="blood_component", create_type=False
            ),
            nullable=False,
        ),
        sa.Column("units", sa.Integer(), nullable=False),
        sa.Column("as_of", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "source",
            postgresql.ENUM("ERAKTKOSH", "SYNTHETIC", name="blood_source", create_type=False),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["hospital_id"], ["hospitals.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "departments",
        sa.Column("hospital_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("specialty_code", sa.String(length=32), nullable=False),
        sa.Column("room_count", sa.SmallInteger(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["hospital_id"], ["hospitals.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=False),
        sa.Column("email", sa.String(length=160), nullable=True),
        sa.Column("password_hash", sa.String(length=200), nullable=True),
        sa.Column(
            "role",
            postgresql.ENUM(
                "ADMIN", "DOCTOR", "STAFF", "PATIENT", name="user_role", create_type=False
            ),
            nullable=False,
        ),
        sa.Column("hospital_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["hospital_id"], ["hospitals.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("phone"),
    )
    op.create_table(
        "doctors",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("hospital_id", sa.UUID(), nullable=False),
        sa.Column("department_id", sa.UUID(), nullable=False),
        sa.Column("specialty", sa.String(length=80), nullable=False),
        sa.Column("badge_id", sa.String(length=64), nullable=False),
        sa.Column("face_enrolled", sa.Boolean(), nullable=False),
        sa.Column("avg_consult_minutes", sa.SmallInteger(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["department_id"], ["departments.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["hospital_id"], ["hospitals.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("badge_id"),
    )
    op.create_table(
        "emergency_requests",
        sa.Column("lat", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("lng", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("specialty_needed", sa.String(length=80), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM("OPEN", "ROUTED", "CLOSED", name="emergency_status", create_type=False),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "footfall_forecasts",
        sa.Column("hospital_id", sa.UUID(), nullable=False),
        sa.Column("department_id", sa.UUID(), nullable=True),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("yhat", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("yhat_lower", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("yhat_upper", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("model_version", sa.String(length=40), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["department_id"], ["departments.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["hospital_id"], ["hospitals.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "footfall_history",
        sa.Column("hospital_id", sa.UUID(), nullable=False),
        sa.Column("department_id", sa.UUID(), nullable=True),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("visits", sa.Integer(), nullable=False),
        sa.Column(
            "source",
            postgresql.ENUM("HMIS", "SYNTHETIC", name="footfall_source", create_type=False),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["department_id"], ["departments.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["hospital_id"], ["hospitals.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "patients",
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=False),
        sa.Column("age", sa.SmallInteger(), nullable=True),
        sa.Column("gender", sa.String(length=16), nullable=True),
        sa.Column("village", sa.String(length=120), nullable=True),
        sa.Column("district", sa.String(length=100), nullable=True),
        sa.Column("priority_flags", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "preferred_language",
            postgresql.ENUM("HI", "EN", name="language", create_type=False),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_patients_phone"), "patients", ["phone"], unique=False)
    op.create_table(
        "zones",
        sa.Column("hospital_id", sa.UUID(), nullable=False),
        sa.Column("department_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column(
            "kind",
            postgresql.ENUM(
                "OPD", "WARD", "OT", "GATE", "LOBBY", name="zone_kind", create_type=False
            ),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["department_id"], ["departments.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["hospital_id"], ["hospitals.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "doctor_status",
        sa.Column("doctor_id", sa.UUID(), nullable=False),
        sa.Column(
            "state",
            postgresql.ENUM(
                "PRESENT_IN_DEPT",
                "PRESENT_ELSEWHERE",
                "ON_ROUNDS",
                "IN_SURGERY",
                "ON_LEAVE",
                "OFF_SHIFT",
                "UNKNOWN",
                name="presence_state",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column("zone_id", sa.UUID(), nullable=True),
        sa.Column("since", sa.DateTime(timezone=True), nullable=False),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["doctor_id"], ["doctors.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["zone_id"], ["zones.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("doctor_id"),
    )
    op.create_table(
        "presence_signals",
        sa.Column("doctor_id", sa.UUID(), nullable=False),
        sa.Column(
            "source",
            postgresql.ENUM(
                "BLE",
                "RFID",
                "FACE",
                "WIFI",
                "ROSTER",
                "MANUAL",
                name="signal_source",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("zone_id", sa.UUID(), nullable=True),
        sa.Column("raw", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("trust", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["doctor_id"], ["doctors.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["zone_id"], ["zones.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_signals_doctor_observed", "presence_signals", ["doctor_id", "observed_at"], unique=False
    )
    op.create_table(
        "presence_transitions",
        sa.Column("doctor_id", sa.UUID(), nullable=False),
        sa.Column(
            "from_state",
            postgresql.ENUM(
                "PRESENT_IN_DEPT",
                "PRESENT_ELSEWHERE",
                "ON_ROUNDS",
                "IN_SURGERY",
                "ON_LEAVE",
                "OFF_SHIFT",
                "UNKNOWN",
                name="presence_state",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "to_state",
            postgresql.ENUM(
                "PRESENT_IN_DEPT",
                "PRESENT_ELSEWHERE",
                "ON_ROUNDS",
                "IN_SURGERY",
                "ON_LEAVE",
                "OFF_SHIFT",
                "UNKNOWN",
                name="presence_state",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["doctor_id"], ["doctors.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "route_rankings",
        sa.Column("emergency_request_id", sa.UUID(), nullable=False),
        sa.Column("hospital_id", sa.UUID(), nullable=False),
        sa.Column("rank", sa.SmallInteger(), nullable=False),
        sa.Column("drive_minutes", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column("capability_score", sa.Numeric(precision=6, scale=3), nullable=False),
        sa.Column("reasons", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["emergency_request_id"], ["emergency_requests.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["hospital_id"], ["hospitals.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "shifts",
        sa.Column("doctor_id", sa.UUID(), nullable=False),
        sa.Column("department_id", sa.UUID(), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "kind",
            postgresql.ENUM(
                "OPD", "WARD", "SURGERY", "ON_CALL", "LEAVE", name="shift_kind", create_type=False
            ),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["department_id"], ["departments.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["doctor_id"], ["doctors.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "slots",
        sa.Column("doctor_id", sa.UUID(), nullable=False),
        sa.Column("department_id", sa.UUID(), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("capacity", sa.SmallInteger(), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM("OPEN", "FULL", "BLOCKED", name="slot_status", create_type=False),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["department_id"], ["departments.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["doctor_id"], ["doctors.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "appointments",
        sa.Column("patient_id", sa.UUID(), nullable=False),
        sa.Column("slot_id", sa.UUID(), nullable=False),
        sa.Column("hospital_id", sa.UUID(), nullable=False),
        sa.Column("department_id", sa.UUID(), nullable=False),
        sa.Column(
            "channel",
            postgresql.ENUM(
                "PWA",
                "WHATSAPP",
                "SMS",
                "IVR",
                "VOICE",
                "KIOSK",
                "STAFF",
                name="channel",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "priority_class",
            postgresql.ENUM(
                "EMERGENCY",
                "REFERRED",
                "PRIORITY",
                "GENERAL",
                name="priority_class",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            postgresql.ENUM(
                "BOOKED",
                "CHECKED_IN",
                "IN_CONSULT",
                "COMPLETED",
                "NO_SHOW",
                "CANCELLED",
                "RESCHEDULED",
                name="appointment_status",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("token_number", sa.Integer(), nullable=True),
        sa.Column("noshow_prob", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column("predicted_wait_min", sa.Integer(), nullable=True),
        sa.Column("rescheduled_from", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["department_id"], ["departments.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["hospital_id"], ["hospitals.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["patient_id"], ["patients.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["rescheduled_from"], ["appointments.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["slot_id"], ["slots.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_appointments_patient_status", "appointments", ["patient_id", "status"], unique=False
    )
    op.create_index("ix_appointments_slot", "appointments", ["slot_id"], unique=False)
    op.create_table(
        "referrals",
        sa.Column("from_hospital_id", sa.UUID(), nullable=False),
        sa.Column("to_hospital_id", sa.UUID(), nullable=False),
        sa.Column("patient_id", sa.UUID(), nullable=False),
        sa.Column("specialty", sa.String(length=80), nullable=False),
        sa.Column(
            "urgency",
            postgresql.ENUM(
                "ROUTINE", "URGENT", "EMERGENCY", name="referral_urgency", create_type=False
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            postgresql.ENUM(
                "REQUESTED",
                "RESERVED",
                "CONFIRMED",
                "ARRIVED",
                "EXPIRED",
                "CANCELLED",
                name="referral_status",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("reserved_bed_id", sa.UUID(), nullable=True),
        sa.Column("reserved_slot_id", sa.UUID(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.String(length=1000), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["from_hospital_id"], ["hospitals.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["patient_id"], ["patients.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["reserved_bed_id"], ["beds.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["reserved_slot_id"], ["slots.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["to_hospital_id"], ["hospitals.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "bed_allocations",
        sa.Column("bed_id", sa.UUID(), nullable=False),
        sa.Column("patient_id", sa.UUID(), nullable=True),
        sa.Column("referral_id", sa.UUID(), nullable=True),
        sa.Column("from_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("to_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["bed_id"], ["beds.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["patient_id"], ["patients.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["referral_id"], ["referrals.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "notifications",
        sa.Column("appointment_id", sa.UUID(), nullable=True),
        sa.Column("patient_id", sa.UUID(), nullable=False),
        sa.Column(
            "channel",
            postgresql.ENUM(
                "PWA",
                "WHATSAPP",
                "SMS",
                "IVR",
                "VOICE",
                "KIOSK",
                "STAFF",
                name="channel",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("template", sa.String(length=80), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("mock", sa.Boolean(), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "QUEUED",
                "SENT",
                "DELIVERED",
                "FAILED",
                name="notification_status",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["appointment_id"], ["appointments.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["patient_id"], ["patients.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "queue_entries",
        sa.Column("appointment_id", sa.UUID(), nullable=False),
        sa.Column("department_id", sa.UUID(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("checked_in_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("called_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "state",
            postgresql.ENUM(
                "WAITING",
                "CALLED",
                "SERVING",
                "DONE",
                "SKIPPED",
                name="queue_state",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["appointment_id"], ["appointments.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["department_id"], ["departments.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("appointment_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("queue_entries")
    op.drop_table("notifications")
    op.drop_table("bed_allocations")
    op.drop_table("referrals")
    op.drop_index("ix_appointments_slot", table_name="appointments")
    op.drop_index("ix_appointments_patient_status", table_name="appointments")
    op.drop_table("appointments")
    op.drop_table("slots")
    op.drop_table("shifts")
    op.drop_table("route_rankings")
    op.drop_table("presence_transitions")
    op.drop_index("ix_signals_doctor_observed", table_name="presence_signals")
    op.drop_table("presence_signals")
    op.drop_table("doctor_status")
    op.drop_table("zones")
    op.drop_index(op.f("ix_patients_phone"), table_name="patients")
    op.drop_table("patients")
    op.drop_table("footfall_history")
    op.drop_table("footfall_forecasts")
    op.drop_table("emergency_requests")
    op.drop_table("doctors")
    op.drop_table("users")
    op.drop_table("departments")
    op.drop_table("blood_stock")
    op.drop_table("beds")
    op.drop_table("plan_runs")
    op.drop_table("hospitals")
    # ### end Alembic commands ###
    sa.Enum(name="queue_state").drop(op.get_bind())
    sa.Enum(name="notification_status").drop(op.get_bind())
    sa.Enum(name="referral_status").drop(op.get_bind())
    sa.Enum(name="referral_urgency").drop(op.get_bind())
    sa.Enum(name="appointment_status").drop(op.get_bind())
    sa.Enum(name="priority_class").drop(op.get_bind())
    sa.Enum(name="channel").drop(op.get_bind())
    sa.Enum(name="slot_status").drop(op.get_bind())
    sa.Enum(name="shift_kind").drop(op.get_bind())
    sa.Enum(name="signal_source").drop(op.get_bind())
    sa.Enum(name="presence_state").drop(op.get_bind())
    sa.Enum(name="zone_kind").drop(op.get_bind())
    sa.Enum(name="language").drop(op.get_bind())
    sa.Enum(name="footfall_source").drop(op.get_bind())
    sa.Enum(name="emergency_status").drop(op.get_bind())
    sa.Enum(name="user_role").drop(op.get_bind())
    sa.Enum(name="blood_source").drop(op.get_bind())
    sa.Enum(name="blood_component").drop(op.get_bind())
    sa.Enum(name="blood_group").drop(op.get_bind())
    sa.Enum(name="bed_state").drop(op.get_bind())
    sa.Enum(name="bed_kind").drop(op.get_bind())
    sa.Enum(name="plan_trigger").drop(op.get_bind())
    sa.Enum(name="hospital_level").drop(op.get_bind())
